name: Deploy to poduction
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Docker Image Tag
        run: |
          echo "IMAGE_TAG=$(cut -c 1-7 <<< $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Get Docker Image Tag
          echo "${{ env.IMAGE_TAG }}
