name: Deploy to Minio

on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    name: sync with bucket
    steps:
      - uses: actions/checkout@v3
      - name: Get Respository Name
        run: |
            echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - name: Sync with Minio Bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
        env:
          AWS_S3_BUCKET: frontend
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          AWS_S3_ENDPOINT: https://minio.techmyteam.net
          SOURCE_DIR: './'
          DEST_DIR: ${{ env.REPOSITORY_NAME }}
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Deployed to staging. Check: https://minio.techmyteam.net/frontend/${{ env.REPOSITORY_NAME }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
