name: Deploy to staging
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Docker Image Tag
        run: |
          echo "IMAGE_TAG=$(cut -c 1-7 <<< $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ambachiri
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ambachiri/github-actions-playground:${{ env.IMAGE_TAG }}
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout manifests repository
        uses: actions/checkouts@v3
        with:
          repository: ambachiri/manifests
          ref: main
          token: ${{ secrets.PAT }}
      - name: Update Image Tag
        run: |
          git config user.name GitHub Actions
          git config user.email github-actions@techmyteam.com
          echo "$IMAGE_TAG" > deployment.yml
          git add .
          git commit -m "Updated Docker Image Tag"
          git push
