name: Deploy to poduction
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show default variables
        run: |
          echo "IMAGE_TAG=$(cut -c 1-7 <<< $GITHUB_SHA)" >> $GITHUB_ENV
          echo "${{ env.IMAGE_TAG }}"
